#!/bin/bash
#
# Script to generate .pot file from C++ sources and XML GUI description file

PROGNAME=kdirstat
SRCDIR=../kdirstat

extractrc --tag=cstring $SRCDIR /*ui.rc >ui_rc.cpp


# search for sourcecode-files
SRCFILES=$(find $SRCDIR . -type f   -name "*.h"   \
                                -o -name "*.c"    \
                                -o -name "*.cc"   \
                                -o -name "*.cpp")

echo "$SRCFILES"

xgettext					\
    --add-comments				\
    --add-location				\
    --keyword=i18n				\
    --keyword=i18n:1,2				\
    --keyword=_					\
    --keyword=_:1,2				\
    --keyword=__				\
    --keyword=N_				\
    --foreign-user				\
    --default-domain=$PROGNAME			\
    --output=PROGNAME.pot			\
    $SRCFILES


